### ISSUE TITLE
This is not the source of the included DLLs in Emby

### ISSUE THREAD

**Issue by berrnd** [MediaBrowser/Emby.Common#2]
This repository can be in fact not the source of the [included DLLs](https://github.com/MediaBrowser/Emby/tree/master/packages/MediaBrowser.Common.3.5.0/lib/netstandard2.0) in Emby.

First example: The MediaBrowser.Model project does not even compile properly in the current state:
```
1>------ Rebuild All started: Project: MediaBrowser.Model, Configuration: Debug Any CPU ------
1>CSC : error CS2001: Source file 'C:\Temp\Emby.Common\MediaBrowser.Model\Properties\AssemblyInfo.cs' could not be found.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

Second example: [Here ](https://github.com/MediaBrowser/Emby/blob/f1998b6aa926269761071990e829ae4f5b351745/MediaBrowser.Api/Library/LibraryService.cs#L1022) is a property `User` of class `AuthorizationInfo` referenced which is itself defined [here ](https://github.com/MediaBrowser/Emby.Common/blob/a6e3ad572da7744f9c81418458a5be3652e710fc/MediaBrowser.Controller/Net/AuthorizationInfo.cs) and has no property `User` in the currently committed version.

Please clarify this.

I find it really strange to move parts in a separate repository and include them as compiled blobs in the main project, especially when they are not the same afterwards. Is there something you want to hide? Or why is this such a fuckup with all the recent and ongoing remarks about the "being Open Source" problems? I understand that maybe it's better to move parts to a separate repository for organization purposes, but why not just include them as GIT submodules or something in the main project instead of compiled blobs? I did this [here](https://github.com/berrnd/Emby/commit/37950db4720d315e18edb17ef57f753412dddc58#diff-8903239df476d7401cf9e76af0252622), works great, when this source here would compile properly...

I want to reference the following related issues:
MediaBrowser/Emby.Common#1
MediaBrowser/Emby#3075
MediaBrowser/Emby#3376

**Comment by LukePulverenti** [comment]
Sorry I had not finished updating it yet. It should be good now. Thanks.

**Comment by berrnd** [comment]
Thanks - and sorry for maybe being too offensive, it just looked a little odd in relation to the referenced issues...
